name: Test
"on":
  push:
    branches:
      - master
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 10
          - 12
          - 14
        os:
          - ubuntu-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: "${{ matrix.node-version }}"
      - uses: bahmutov/npm-install@v1
      - run: "npm run test:ci"
  test:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: "${{ matrix.node-version }}"
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
      - run: npx lockfile-lint --path package-lock.json
